[Details]
Icon = "assets/logo.png"
Name = "fToDo"
ID = "com.emarifer.ftodo"
Version = "1.0.0"
Build = 1

[LinuxAndBSD]
Categories = ["Development"]
Comment = "Golang desktop todo app using Fyne UI framework."
